### ISSUE TITLE
Revo LDS geometry inorrect

### ISSUE THREAD

**Issue by gaborszita** [bmegli/xv11lidar-test#8]
Hi!

I was working on the lidar geometry correction, I followed your formula on the [Image](https://www.ev3dev.org/images/xv11-tutorial/lidar_rotational_geometry.png),but it didn't work for me. I found out *180 - 82 + angle* isn't correct. It should be: *180 - (82 + angle)*

Gabor Szita

**Comment by bmegli** [comment]
Hi @gaborszita!

The formula and image come directly from:
- [Revo LDS whitepaper](http://www.robotshop.com/media/files/PDF/revolds-whitepaper.pdf)
- and from Neato patent US8996172 

But yes, you are correct that you have to play with the signs to get it right for your case.
It also depends how you see the axes (which is X, which is Y with respect to lidar).

Generally you can test with raw data here:
https://github.com/bmegli/xv11lidar-test/blob/master/xv11plot.ods
(the Y axis there is along longer dimension of lidar, different from the image) 

See also similiar issue https://github.com/bmegli/ev3dev-mapping/issues/4

**Comment by gaborszita** [comment]
Thanks, bmegli. Sorry for the long reply, I didn't visited github for a long time.

Gabor Szita
