### ISSUE TITLE
/dev/tty_in1: No such file or directory and motor is not spinning

### ISSUE THREAD

**Issue by asanebub** [bmegli/xv11lidar-test#9]
Hello @bmegli,

I'm trying to test the xv11 lidar-sensor with ev3, like it's mentioned here: https://www.ev3dev.org/docs/tutorials/using-xv11-lidar/:

When I'm doing: `echo other-uart > /sys/class/lego-port/port0/mode`, then there isn't a folder /dev/tty_in1. I just have: tty_ev3-ports:in1

Here you can see the output of the commands:

![dev_tty_in1](https://user-images.githubusercontent.com/44498471/78991975-894bfe80-7b3a-11ea-9a27-b1cc871ab332.png)

![dev](https://user-images.githubusercontent.com/44498471/78992485-a208e400-7b3b-11ea-845a-77ac19dcc17d.png)

Additionally the motor is not spinning, when I do:
```
echo 44 > /sys/class/dc-motor/motor0/duty_cycle_sp
echo run-direct > /sys/class/dc-motor/motor0/command
```

How can I solve these problems?

**Comment by bmegli** [comment]
First - this program was written more than 4 years ago.\
Many ev3dev versions were released during this period.

Some things (obviously tty paths) changed.

I am assuming you are using the ev3dev-strech.

# The motor

I have just tested it with ev3dev-strech-2019-10-29.

Initial setup (once after boot)

```bash
echo dc-motor > /sys/class/lego-port/port4/mode #for output A, otherwise adjust the port number
dmesg | tail #you can see here which number the dc-motor  was created with
cat /sys/class/dc-motor/motorX/address # where X is the motor number, make sure the address matches the port
```

Controlling the motor

Assuming it is the motor0

```bash
echo 44 > /sys/class/dc-motor/motor0/duty_cycle_sp
echo run-direct > /sys/class/dc-motor/motor0/command
```

If it doesn't spin try with -44.

E.g.

```bash
echo -44 > /sys/class/dc-motor/motor0/duty_cycle_sp
echo run-direct > /sys/class/dc-motor/motor0/command
```

It is critical that the motor spins counter-clockwise.

If it doesn't work make sure it is soldered correctly.

See also #1.

# The sensor

I have also just tested it with ev3dev-strech-2019-10-29.

Yes, obviously you are right.

The notation in ev3dev-stretch is `tty_ev3-ports:in1`

So it will be:

Once after boot:

```bash
echo other-uart > /sys/class/lego-port/port0/mode
```

And to read from lidar:

```bash
./xv11test /dev/tty_ev3-ports\:in1
```

Note that, for this to work it is critical that motor spins CCW.

**Comment by asanebub** [comment]
It worked with `./xv11test /dev/tty_ev3-ports\:in1`

Thank you! :)
